language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0

matrix:
  fast_finish: true

script:
  - composer update-all
  - composer show -i
  - composer test

  # Visual tests
  - php ./bin/jbzoo
  - php ./bin/jbzoo test
  - php ./bin/jbzoo test --option=ytrewq

after_script:
  - composer coveralls
